### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by kmcrawford** [opencomponents/oc#1086]
## *Who* is the bug affecting?
Registry hangs on errors

## *What* is affected by this bug?
browser client, and registry server

## *When* does this occur?
During parsing error.

## *Where* on the platform does it happen?
Registry, unable to reproduce

## *How* do we replicate the issue?
Unable to reproduce

## Expected behavior (i.e. solution)
Error with logging 

## What version of OC, Node.js and OS are you using?
Registry 0.48.1, alpine linux

## Other Comments
Logs from the registry.  I am sure there is invalid code causing this, but oc should be able to handle this and not throw this error.

```
(node:1) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at stringify (/app/node_modules/express/lib/response.js:1119:12)
    at ServerResponse.json (/app/node_modules/express/lib/response.js:260:14)
    at async.map (/app/node_modules/oc/src/registry/routes/components.js:72:25)
```

**Comment by kmcrawford** [comment]
I have this code running in production and it has kept our registry from hanging on requests & due to the console.log we can now see which component/team is responsible.  However I'd like this to be considered to be merged in, I can don't have forked code.
